# Generated by Django 6.1 on 2026-08-15 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
